load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "TopologicalSortBoost",
    srcs = ["TopologicalSortBoost.cpp"],
    deps = ["@boost//:graph"],
)

cc_binary(
    name = "SingleSourceShortestPathBoost",
    srcs = ["SingleSourceShortestPathBoost.cpp"],
    deps = ["@boost//:graph"],
)
