load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "edge_basics",
    srcs = ["edge_basics.cpp"],
    deps = ["@boost//:graph"],
)

cc_binary(
    name = "DFS",
    srcs = ["DFS.cpp"],
    deps = ["@boost//:graph"],
)
